In [15]:
import torch

In [16]:
x=torch.tensor([2,3,4,5])
y=torch.tensor([10,9,8,6])
x+y,x-y,x*y,x/y,x**y

(tensor([12, 12, 12, 11]),
 tensor([-8, -6, -4, -1]),
 tensor([20, 27, 32, 30]),
 tensor([0.2000, 0.3333, 0.5000, 0.8333]),
 tensor([ 1024, 19683, 65536, 15625]))

In [17]:
torch.exp(x)

tensor([  7.3891,  20.0855,  54.5981, 148.4132])

In [18]:
x=torch.arange(12,dtype=torch.float32).reshape(3,4)
y=torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  5.,  6.,  7.,  8.],
         [ 8.,  9., 10., 11.,  9., 10., 11., 12.]]))

In [19]:
x==y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
x.sum()

tensor(66.)

In [22]:
x=torch.tensor([[0],[1],[2]])
y=torch.tensor([1,2])
x,y,x+y

(tensor([[0],
         [1],
         [2]]),
 tensor([1, 2]),
 tensor([[1, 2],
         [2, 3],
         [3, 4]]))

In [23]:
x=torch.arange(16,dtype=torch.float32).reshape(4,4)
x[1,2]=9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [25]:
x[1:3,:]

tensor([[ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [27]:
x=torch.tensor([1,2,3,4])
y=torch.tensor([4,5,6,7])
z=torch.zeros_like(y)
before=id(z)
z[:]=x+y
id(z)==before


True

In [28]:
print(id(x))
x+=y
print(id(x))

2165325667632
2165325667632


In [29]:
a=x.numpy()
b=torch.tensor(a)
type(a),type(b)

(numpy.ndarray, torch.Tensor)