In [1]:
import torch

In [3]:
x=torch.arange(4,dtype=torch.float32)
x.requires_grad_(True)
x.grad

In [4]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [5]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad.zero_()
y=x.sum()    #y=x1+x2
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x=torch.tensor([1.0,2.0],requires_grad=True)
y=x**2         #y=[x1^2,x2^2]  
y.backward(torch.tensor([1.0,1.0]))  #v*jacobian 将y对x的雅可比矩阵乘以v
x.grad

tensor([2., 4.])

In [9]:
def f(x):
    return x**2

x=torch.tensor([1.0,2.0],requires_grad=True)
y=f(x)
j=torch.autograd.functional.jacobian(f,x)
print(j)

tensor([[2., 0.],
        [0., 4.]])
