In [1]:
import torch 
from torch import nn

net = nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,1))
x=torch.rand(size=(2,4))
net(x)

tensor([[0.0229],
        [0.0106]], grad_fn=<AddmmBackward0>)

In [2]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[-0.1634,  0.0090, -0.2384, -0.2332,  0.1337, -0.1297, -0.0458, -0.0184]])), ('bias', tensor([0.0234]))])


In [ ]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)


<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.0234], requires_grad=True)
tensor([0.0234])


In [4]:
net[2].weight.grad == None

True

In [5]:
for name,param in net.named_parameters():
    print(f'name:{name} param:{param} \n')

name:0.weight param:Parameter containing:
tensor([[ 0.2935,  0.0455, -0.2083, -0.4550],
        [-0.4046,  0.2035,  0.3208, -0.3400],
        [ 0.3856, -0.2429,  0.2351,  0.2652],
        [ 0.1209, -0.3007, -0.0461, -0.4430],
        [-0.1942,  0.4937,  0.3996, -0.3929],
        [ 0.2189,  0.0650, -0.0272,  0.1086],
        [ 0.1250, -0.1602, -0.0724, -0.3751],
        [ 0.3516, -0.4516, -0.0778,  0.3075]], requires_grad=True) 

name:0.bias param:Parameter containing:
tensor([ 0.2108,  0.3569, -0.3849,  0.3182, -0.0892, -0.1757, -0.1513, -0.4784],
       requires_grad=True) 

name:2.weight param:Parameter containing:
tensor([[-0.1634,  0.0090, -0.2384, -0.2332,  0.1337, -0.1297, -0.0458, -0.0184]],
       requires_grad=True) 

name:2.bias param:Parameter containing:
tensor([0.0234], requires_grad=True) 



In [6]:
net.state_dict()['2.bias'].data

tensor([0.0234])

In [7]:
def block1():
    return nn.Sequential(nn.Linear(4,8),nn.ReLU(),nn.Linear(8,4),nn.ReLU())


def block2():
    net=nn.Sequential()
    for i in range(4):
        net.add_module(f'blcok {i}',block1())
    return net

net=nn.Sequential(block2(),nn.Linear(4,1))
net(x)

tensor([[-0.6027],
        [-0.6027]], grad_fn=<AddmmBackward0>)

In [8]:
print(net)

Sequential(
  (0): Sequential(
    (blcok 0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (blcok 1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (blcok 2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (blcok 3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [9]:
net[0][1][0].bias.data

tensor([-0.1774,  0.4550, -0.1463,  0.0189,  0.1678, -0.0272, -0.3195, -0.3564])